services:
  dashboard:
    image: mdawar/nats-dashboard
    build:
      context: .
      dockerfile: Dockerfile
      target: main
      args:
        # Pass the env variables as build args.
        - SITE_DOMAIN
    ports:
      - target: 80
        published: 8000
        protocol: tcp

  server:
    image: nats:2.10
    command: -n local-demo-server -m 8222 -js
    ports:
      - target: 4222
        published: 4222
        protocol: tcp
      - target: 8222
        published: 8222
        protocol: tcp
